name: update readme

on:
  schedule:
    # midnight est is 0500 utc
    - cron: "0 5 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v5
      - name: generate 3d profile contrib 
        uses: johnlarkin1/github-profile-3d-contrib@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
          MAX_REPOS: 150
          SETTING_JSON: ./default-profile-settings.json
          EXCLUDED_LANGUAGES: HTML

      - name: Commit and push changes
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add profile-3d-contrib/
          git diff --staged --quiet || git commit -m "update 3d profile contrib (daily)"
          git push